# Generated by Django 2.0.8 on 2018-11-10 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestIntroduce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduce_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OfuroResult',
            fields=[
                ('result_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=20)),
                ('image_url_L', models.CharField(max_length=200)),
                ('image_url_S', models.CharField(max_length=200)),
                ('share_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='guestintroduce',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofuro.OfuroResult'),
        ),
    ]
