# Generated by Django 2.0.8 on 2018-11-10 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofuro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestintroduce',
            name='introduce_url',
            field=models.CharField(default='https://twitter.com/d_one_zwei', max_length=500),
            preserve_default=False,
        ),
    ]
