# Generated by Django 2.0.8 on 2018-11-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofuro', '0003_auto_20181111_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestintroduce',
            name='introduce_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='guestintroduce',
            name='introduce_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
