# Generated by Django 2.0.8 on 2018-11-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofuro', '0004_auto_20181111_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestintroduce',
            name='introduce_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='guestintroduce',
            name='introduce_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
