# Generated by Django 2.0.8 on 2018-11-14 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofuro', '0007_auto_20181114_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ofuroresult',
            old_name='image_url_L',
            new_name='image_L',
        ),
        migrations.RenameField(
            model_name='ofuroresult',
            old_name='image_url_S',
            new_name='image_S',
        ),
    ]
